name: Code Formatter (Black + isort)

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install format tools
        run: |
          python -m pip install --upgrade pip
          pip install black isort

      - name: Run isort
        run: isort .

      - name: Run Black
        run: black .